############DEBUGGING#####################

# # Describe Problem
# def my_function():
#   for i in range(1, 20): # FIX for i in range(1, 21):
#     if i == 20:
#       print("You got it")
# my_function()

# # Reproduce the Bug
# from random import randint
# dice_imgs = ["❶", "❷", "❸", "❹", "❺", "❻"]
# BUG! reproduce by setting `dice_num` to all the possible values generated by randint
# dice_num = randint(1, 6) 
# FIX
# dice_num = randint(0, 5) 
# print(dice_imgs[dice_num])

# # Play Computer (by replacing variables w/ values set by input)
# It breaks w/ 1994 as input. FIX by setting the second condition to # elif year > 1994:
# year = int(input("What's your year of birth?"))
# year = 1994
# if year > 1980 and year < 1994:
#   print("You are a millenial.")
# elif year > 1994:
#   print("You are a Gen Z.")

# # Fix the Errors (wrong indentation, string used as integer, and fString in print stmt)
# age = input("How old are you?")
# if age > 18:
# print("You can drive at age {age}.")

# #Print is Your Friend (used it to spot the bug -> `word_per_page ==` instead of `word_per_page =`)
# pages = 0
# word_per_page = 0
# pages = int(input("Number of pages: "))
# word_per_page == int(input("Number of words per page: "))
# total_words = pages * word_per_page
# print(total_words)

#Use a Debugger (and find out that line must be indented to the for loop: `b_list.append(new_item)`)
def mutate(a_list):
  b_list = []
  for item in a_list:
    new_item = item * 2
  b_list.append(new_item)
  print(b_list)

mutate([1,2,3,5,8,13])